#!/bin/bash

# Generate docker-compose.override.yml with per-agent workspace volumes
# This allows each agent instance to have its own isolated workspace directory

set -e

# Source workspace utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/workspace-utils.sh"

# Output file
OUTPUT_FILE="$SCRIPT_DIR/docker-compose.override.yml"

# Agent counts (passed as arguments or defaults to 0)
CLAUDE_COUNT=${1:-0}
CODEX_COUNT=${2:-0}
AIDER_COUNT=${3:-0}
OPENCODE_COUNT=${4:-0}
AUTH_TYPE=${5:-api_key}

# Color output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${BLUE}[COMPOSE-GEN]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[COMPOSE-GEN]${NC} $1"
}

# Generate service definition for a single agent instance
generate_agent_service() {
    local service_name="$1"
    local instance_num="$2"
    local workspace_mount="$3"
    local agent_type="$4"

    local agent_id="${service_name}-${instance_num}"
    local workspace_path=$(ensure_agent_workspace "$agent_id")

    # Determine workspace mount point and user paths in container based on agent type
    local container_workspace=""
    local ssh_path=""
    local git_path=""
    case "$agent_type" in
        claude-code)
            container_workspace="/home/claude/workspace"
            ssh_path="/home/claude/.ssh"
            git_path="/home/claude/.gitconfig"
            ;;
        openai-codex|aider|opencode)
            if [ "$agent_type" = "openai-codex" ]; then
                container_workspace="/codex-workspace"
            elif [ "$agent_type" = "aider" ]; then
                container_workspace="/aider-workspace"
            else
                container_workspace="/opencode-workspace"
            fi
            ssh_path="/root/.ssh"
            git_path="/root/.gitconfig"
            ;;
    esac

    cat <<EOF
  $agent_id:
    extends:
      file: docker-compose.yml
      service: $service_name
    container_name: docker-$agent_id
    volumes:
      - $workspace_path:$container_workspace
      - \${HOME}/.ssh:$ssh_path:ro
      - \${HOME}/.gitconfig:$git_path:ro
EOF

    # Add ollama-data volume for opencode
    if [ "$agent_type" = "opencode" ]; then
        echo "      - ollama-data:/root/.ollama"
    fi
}

# Start generating the override file
print_info "Generating docker-compose.override.yml..."
print_info "Agent counts: Claude=$CLAUDE_COUNT, Codex=$CODEX_COUNT, Aider=$AIDER_COUNT, OpenCode=$OPENCODE_COUNT"

cat > "$OUTPUT_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
# Generated by generate-compose-override.sh
# This file provides per-agent workspace isolation

version: '3.8'

services:
HEADER

# Generate claude-code instances
if [ "$CLAUDE_COUNT" -gt 0 ]; then
    for i in $(seq 1 $CLAUDE_COUNT); do
        generate_agent_service "claude-code" "$i" "/home/claude/workspace" "claude-code" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
fi

# Generate openai-codex instances
if [ "$CODEX_COUNT" -gt 0 ]; then
    for i in $(seq 1 $CODEX_COUNT); do
        generate_agent_service "openai-codex" "$i" "/codex-workspace" "openai-codex" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
fi

# Generate aider instances
if [ "$AIDER_COUNT" -gt 0 ]; then
    for i in $(seq 1 $AIDER_COUNT); do
        generate_agent_service "aider" "$i" "/aider-workspace" "aider" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
fi

# Generate opencode instances
if [ "$OPENCODE_COUNT" -gt 0 ]; then
    for i in $(seq 1 $OPENCODE_COUNT); do
        generate_agent_service "opencode" "$i" "/opencode-workspace" "opencode" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done

    # Add volumes section for ollama-data
    cat >> "$OUTPUT_FILE" <<'VOLUMES'

volumes:
  ollama-data:
    driver: local
VOLUMES
fi

# Check if any services were generated
TOTAL_AGENTS=$((CLAUDE_COUNT + CODEX_COUNT + AIDER_COUNT + OPENCODE_COUNT))
if [ "$TOTAL_AGENTS" -eq 0 ]; then
    # Add empty object to make valid YAML when no services are defined
    cat >> "$OUTPUT_FILE" <<'EMPTY'
  # No agent services configured
  # When scaling to zero, all agent containers will be stopped
  {}
EMPTY
fi

print_success "Generated $OUTPUT_FILE"
print_info "Workspace root: $(get_workspace_root)"
